import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;


// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1AbjCS2MG5UMORVf7zL_R6iySP2oiIlM',
    appId: '1:579522921542:web:06b46b19928780618b7647',
    messagingSenderId: '579522921542',
    projectId: 'push-alam-d1319',
    authDomain: 'push-alam-d1319.firebaseapp.com',
    storageBucket: 'push-alam-d1319.firebasestorage.app',
    measurementId: 'G-9EVVLXM12H',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsQtrvWX1fU9I6U7pmMH9kXRc-8r4rVOs',
    appId: '1:579522921542:ios:762652efd8be07748b7647',
    messagingSenderId: '579522921542',
    projectId: 'push-alam-d1319',
    storageBucket: 'push-alam-d1319.firebasestorage.app',
    iosBundleId: 'com.example.aMicroDivide',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsQtrvWX1fU9I6U7pmMH9kXRc-8r4rVOs',
    appId: '1:579522921542:ios:762652efd8be07748b7647',
    messagingSenderId: '579522921542',
    projectId: 'push-alam-d1319',
    storageBucket: 'push-alam-d1319.firebasestorage.app',
    iosBundleId: 'com.example.aMicroDivide',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1AbjCS2MG5UMORVf7zL_R6iySP2oiIlM',
    appId: '1:579522921542:web:df74048c2e7bc39b8b7647',
    messagingSenderId: '579522921542',
    projectId: 'push-alam-d1319',
    authDomain: 'push-alam-d1319.firebaseapp.com',
    storageBucket: 'push-alam-d1319.firebasestorage.app',
    measurementId: 'G-093ZKH3GZN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANqhIyaaGHkklt5q-0u6OHulXlpPeBTD4',
    appId: '1:579522921542:android:4f463277abea2cee8b7647',
    messagingSenderId: '579522921542',
    projectId: 'push-alam-d1319',
    storageBucket: 'push-alam-d1319.firebasestorage.app',
  );

}