-- 장바구니 아이템을 저장하는 테이블을 생성합니다.
CREATE TABLE public.cart_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    -- 어떤 사용자의 장바구니 아이템인지 (users 테이블과 연결)
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    -- 어떤 상품을 담았는지 (products 테이블과 연결)
    product_id BIGINT NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,
    -- 몇 개를 담았는지
    quantity INT NOT NULL CHECK (quantity > 0),
    -- 한 사용자가 같은 상품을 중복해서 담는 것을 방지합니다. (대신 수량을 업데이트해야 함)
    UNIQUE(user_id, product_id)
);

-- RLS(행 수준 보안)를 활성화합니다.
ALTER TABLE public.cart_items ENABLE ROW LEVEL SECURITY;

-- 사용자는 자신의 장바구니 아이템만 보고 수정/삭제할 수 있다는 정책을 추가합니다.
CREATE POLICY "Users can manage their own cart items"
ON public.cart_items
FOR ALL
USING ( auth.uid() = user_id )
WITH CHECK ( auth.uid() = user_id );