-- 찜한 상품 목록을 저장하는 테이블을 생성합니다.
CREATE TABLE public.wishlist_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    -- 어떤 사용자가 찜했는지 (users 테이블과 연결)
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    -- 어떤 상품을 찜했는지 (products 테이블과 연결)
    product_id BIGINT NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,
    -- 한 사용자가 같은 상품을 중복해서 찜하는 것을 방지합니다.
    UNIQUE(user_id, product_id)
);

-- RLS(행 수준 보안)를 활성화합니다.
ALTER TABLE public.wishlist_items ENABLE ROW LEVEL SECURITY;

-- 사용자는 자신의 찜 목록만 보고 관리(추가/삭제)할 수 있다는 정책을 추가합니다.
CREATE POLICY "Users can manage their own wishlist items"
ON public.wishlist_items
FOR ALL
USING ( auth.uid() = user_id )
WITH CHECK ( auth.uid() = user_id );