-- 1. 옵션 그룹 테이블 ('색상', '사이즈' 등)
CREATE TABLE public.product_options (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,
    name TEXT NOT NULL -- 예: '색상', '사이즈'
);

-- 2. 개별 옵션 항목 테이블 ('레드', 'S' 등)
CREATE TABLE public.product_option_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    option_id BIGINT NOT NULL REFERENCES public.product_options(id) ON DELETE CASCADE,
    name TEXT NOT NULL, -- 예: '레드', 'S'
    additional_price INT NOT NULL DEFAULT 0, -- 옵션에 따른 추가 금액
    stock_quantity INT NOT NULL -- 옵션별 재고
);

-- RLS(행 수준 보안) 활성화
ALTER TABLE public.product_options ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.product_option_items ENABLE ROW LEVEL SECURITY;

-- 3. 정책 추가 (모든 사용자가 옵션 정보를 볼 수 있도록 허용)
CREATE POLICY "Allow public read access to options"
ON public.product_options FOR SELECT
USING (true);

CREATE POLICY "Allow public read access to option items"
ON public.product_option_items FOR SELECT
USING (true);

-- 관리자(로그인한 사용자)만 옵션을 생성, 수정, 삭제할 수 있도록 허용
CREATE POLICY "Allow authenticated users to manage options"
ON public.product_options FOR ALL
USING (true)
WITH CHECK (true);

CREATE POLICY "Allow authenticated users to manage option items"
ON public.product_option_items FOR ALL
USING (true)
WITH CHECK (true);