# a_nanum/.github/workflows/deploy_admin.yml (전체 교체)

name: Deploy Admin Web to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      # ⭐️ 1. GitHub Secrets를 사용하여 .env 파일을 동적으로 생성하는 단계 추가
      - name: Create .env file
        run: |
          cd nanum_admin
          echo "SUPABASE_URL=${{ secrets.SUPABASE_URL }}" >> .env
          echo "SUPABASE_ANON_KEY=${{ secrets.SUPABASE_ANON_KEY }}" >> .env
      
      # ⭐️ 1. (디버깅용) 현재 폴더의 모든 파일 목록을 출력합니다.
      - name: List files
        run: ls -R

      # ⭐️ 2. nanum_admin 폴더로 이동하여 빌드합니다.
      - name: Build Admin Web
        run: |
          cd nanum_admin
          flutter pub get
          flutter build web --release --base-href /a_nanum/
        
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # ⭐️ 3. 배포할 폴더 경로도 nanum_admin으로 수정합니다.
          publish_dir: ./nanum_admin/build/web